name: flask-demo-stocks
dependencies:
  - scipy=0.16.0
  - numpy=1.9.2
  - pandas=0.16.2
  - bokeh=0.11.1
  - Cython==0.23.1
  - decorator==4.0.2
  - dill==0.2.4
  - Flask==0.10.1
  - futures==3.0.3
  - Jinja2==2.8
  - jsonschema==2.4.0
  - matplotlib==1.4.3
  - requests==2.7.0
  - seaborn==0.6.0
  - simplejson==3.8.0

